test-new-fieldaccessdiff-plugin-changes

diff --git a/.github/workflows/upload-object-changes.yaml b/.github/workflows/upload-object-changes.yaml
--- a/.github/workflows/upload-object-changes.yaml
+++ b/.github/workflows/upload-object-changes.yaml
@@ -5,6 +5,9 @@ on:
   push:
     branches:
       - develop
+  pull_request:
+    branches:
+      - develop
 permissions:
   contents: "read"
   id-token: "write"
@@ -34,7 +37,7 @@ jobs:
           repository: anzx/salesforce-doc-gen
           token: ${{ secrets.SALESFORCE_DOC_GEN_TOKEN }}
           path: plugin
-          ref: e2ea86e0a326309dd6422d866e70d1f35b4d227b
+          ref: 1a1d6b3abd898fbd769f6f60a9c67627542a6e13
           # this is a particular commit on master. Change this when a new plugin version is required for doc:fieldsaccessdiff
 
       - name: Install npm packages
@@ -183,24 +186,24 @@ jobs:
           zip -r $ARTIFACT_NAME output && ls -la
           curl -H "Authorization: Bearer ${{ steps.secrets.outputs.artifactory_token }}" -X PUT -T "$ARTIFACT_NAME.zip" "https://artifactory.gcp.anz/artifactory/anzx-salesforce-releases-np/$ARTIFACT_NAME.zip"
 
-      # Upload Changes to GCS
-      - name: Upload Changes to GCS SIT
-        id: "upload-folder-to-gcs"
-        if: ${{ (steps.run-diff.outputs.CHANGES_DETECTED == 'TRUE' && steps.run-diff.outcome == 'success' && steps.pull-from-gcs.outcome == 'success' && steps.push-success-to-artifactory.outcome == 'success') && !cancelled() }}
-        working-directory: salesforce
-        shell: bash
-        run: |
-          object_array=($(find output/ -maxdepth 1 -mindepth 1 -type d -exec basename {} \;))
-          for object in "${object_array[@]}"; do
-            if ! output=$(gcloud storage rm -r gs://${{ env.BUCKET_NAME }}/$object/** 2>&1); then
-              if echo "$output" | grep -q "The following URLs matched no objects or files"; then
-                echo "No files or folders found to remove."
-              else
-                echo "An error occurred during gsutil copy."
-                exit 1
-              fi
-            else
-              echo "$output"
-            fi
-            gsutil -m cp -r output/$object/* gs://${{ env.BUCKET_NAME }}/$object/
-          done
+      # # Upload Changes to GCS
+      # - name: Upload Changes to GCS SIT
+      #   id: "upload-folder-to-gcs"
+      #   if: ${{ (steps.run-diff.outputs.CHANGES_DETECTED == 'TRUE' && steps.run-diff.outcome == 'success' && steps.pull-from-gcs.outcome == 'success' && steps.push-success-to-artifactory.outcome == 'success') && !cancelled() }}
+      #   working-directory: salesforce
+      #   shell: bash
+      #   run: |
+      #     object_array=($(find output/ -maxdepth 1 -mindepth 1 -type d -exec basename {} \;))
+      #     for object in "${object_array[@]}"; do
+      #       if ! output=$(gcloud storage rm -r gs://${{ env.BUCKET_NAME }}/$object/** 2>&1); then
+      #         if echo "$output" | grep -q "The following URLs matched no objects or files"; then
+      #           echo "No files or folders found to remove."
+      #         else
+      #           echo "An error occurred during gsutil copy."
+      #           exit 1
+      #         fi
+      #       else
+      #         echo "$output"
+      #       fi
+      #       gsutil -m cp -r output/$object/* gs://${{ env.BUCKET_NAME }}/$object/
+      #     done
