add validate_object_changes workflow

diff --git a/.github/workflows/upload-object-changes.yaml b/.github/workflows/upload-object-changes.yaml
--- a/.github/workflows/upload-object-changes.yaml
+++ b/.github/workflows/upload-object-changes.yaml
@@ -99,7 +99,7 @@ jobs:
             for err in "${errors[@]}"; do
                 echo "$err"
             done
-            exit 1  # Optional: Exit with a non-zero status
+            exit 1 # Exit with a non-zero status
           fi
 
       # Upload to artifactory
