handle errors

diff --git a/.github/workflows/upload-object-changes.yaml b/.github/workflows/upload-object-changes.yaml
--- a/.github/workflows/upload-object-changes.yaml
+++ b/.github/workflows/upload-object-changes.yaml
@@ -82,22 +82,25 @@ jobs:
           odaseva_object_list=$(jq -r '.odaseva_object_whitelist[]' ./config/object-changes-list.json)
 
           for object in $sfdatasync_object_list; do
-            ../plugin/bin/run doc:fieldsaccessdiff -a sfdatasync.user@anzx.com.test24 -e ./bigq_exclusionfile.json -o $object \
-                -f sfdatasync_user_output -u tech.gcb@anzx.com.test24 || true
+            if  ! ../plugin/bin/run doc:fieldsaccessdiff -a sfdatasync.user@anzx.com.test24 -e ./bigq_exclusionfile.json -o $object \
+                  -f sfdatasync_user_output -u tech.gcb@anzx.com.test24; then
+                errors+=("$object")
+            fi
           done
           for object in $sfdatasync_object_list; do
-          ../plugin/bin/run doc:fieldsaccessdiff -a odaseva.user@anzx.com.test24 -e ./bigq_exclusionfile.json -o $object \
-              -f odaseva_user_output -u tech.gcb@anzx.com.test24 || true
+            if  ! ../plugin/bin/run doc:fieldsaccessdiff -a odaseva.user@anzx.com.test24 -e ./bigq_exclusionfile.json -o $object \
+                  -f odaseva_user_output -u tech.gcb@anzx.com.test24; then
+                errors+=("$object")
+            fi
           done
 
-      # # Login to registry
-      # - name: "Registry Authentication"
-      #   uses: "docker/login-action@v3"
-      #   if: ${{ always() }}
-      #   with:
-      #     registry: "salesforce-docker.artifactory.gcp.anz"
-      #     username: "robot-salesforce-ci"
-      #     password: "${{ steps.secrets.outputs.artifactory_token }}"
+          if [ ${#errors[@]} -ne 0 ]; then
+            echo "Errors occurred with the following objects:"
+            for err in "${errors[@]}"; do
+                echo "$err"
+            done
+            exit 1  # Optional: Exit with a non-zero status
+          fi
 
       # Upload to artifactory
       - name: Push changes to artifactory
@@ -107,7 +110,7 @@ jobs:
         shell: bash
         run: |
           # zip the files
-          mkdir output && mv sfdatasync_output odaseva_output output/
+          mkdir output && mv sfdatasync_user_output odaseva_user_output output/
           ARTIFACT_NAME="sf_objects_diff_$(echo "${{ github.sha }}" | cut -c1-7)_${{ github.run_id }}"
           echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
 
