updating var names and logs

diff --git a/.github/workflows/validate-object-changes.yaml b/.github/workflows/validate-object-changes.yaml
--- a/.github/workflows/validate-object-changes.yaml
+++ b/.github/workflows/validate-object-changes.yaml
@@ -32,17 +32,16 @@ jobs:
         shell: bash
         run: |
           ARTIFACTORY_ARTIFACT_NAME="sf_objects_success_diff_develop_${{ github.event.pull_request.head.sha }}"
-          echo "ARTIFACTORY_ARTIFACT_NAME=$ARTIFACTORY_ARTIFACT_NAME"
+          echo "ARTIFACTORY_ARTIFACT_LINK=https://artifactory.gcp.anz/artifactory/ \
+          anzx-salesforce-releases-np/$ARTIFACTORY_ARTIFACT_NAME.zip"
 
-          status_code=
-          if  ! status_code=$(wget --server-response -P artifactory_success_output/ "https://artifactory.gcp.anz/artifactory/ \
-                anzx-salesforce-releases-np/$ARTIFACTORY_ARTIFACT_NAME.zip" 2>&1 | awk '/HTTP\// {print $2}' | tail -n 1); then
+          if  ! status_code=$(wget --server-response -P artifactory_success_output/ "$ARTIFACTORY_ARTIFACT_LINK" 2>&1 | awk '/HTTP\// {print $2}' | tail -n 1); then
               echo "Error when pulling artifact from artifactory. Received HTTP status code when pulling: $status_code"
           fi
           if [ "$status_code" -eq 200 ]; then
             unzip artifactory_success_output/$ARTIFACTORY_ARTIFACT_NAME.zip -d artifactory_success_output
           elif [ "$status_code" -eq 404 ]; then
-              echo "Error: File not found (Status code: $status_code). This means that the upload-object-changes.yml workflow was not run on ${{ github.sha }} as a post deployment step on the develop branch. If this was a commit for a conflict fix on master, please merge it into develop first and then run the upload-object-changes.yml workflow on the develop branch. You can then re-run this workflow."
+              echo "Error: File not found (Status code: $status_code). This means that the upload-object-changes.yml workflow was not run on ${{ github.event.pull_request.head.sha }} as a post deployment step on the develop branch. If this was a commit for a conflict fix on master, please merge it into develop first and then run the upload-object-changes.yml workflow on the develop branch. You can then re-run this workflow."
               echo "wget threw error with status code: $status_code"
               exit 1
           else
