additional error handling on artifactory pull

diff --git a/.github/workflows/validate-object-changes.yaml b/.github/workflows/validate-object-changes.yaml
--- a/.github/workflows/validate-object-changes.yaml
+++ b/.github/workflows/validate-object-changes.yaml
@@ -34,18 +34,22 @@ jobs:
           ARTIFACTORY_ARTIFACT_NAME="sf_objects_success_diff_develop_${{ github.event.pull_request.head.sha }}"
           echo "ARTIFACTORY_ARTIFACT_NAME=$ARTIFACTORY_ARTIFACT_NAME"
 
-          wget --server-response -P artifactory_success_output/ "https://artifactory.gcp.anz/artifactory/anzx-salesforce-releases-np/$ARTIFACTORY_ARTIFACT_NAME.zip" 2>&1 | awk '/HTTP\// {print $2}' | tail -n 1
-          status_code=$(wget --server-response -P artifactory_success_output/ "https://artifactory.gcp.anz/artifactory/anzx-salesforce-releases-np/$ARTIFACTORY_ARTIFACT_NAME.zip" 2>&1 | awk '/HTTP\// {print $2}' | tail -n 1)
-          echo status_code="$status_code"
+          status_code=
+          if  ! status_code=$(wget --server-response -P artifactory_success_output/ "https://artifactory.gcp.anz/artifactory/ \
+                anzx-salesforce-releases-np/$ARTIFACTORY_ARTIFACT_NAME.zip" 2>&1 | awk '/HTTP\// {print $2}' | tail -n 1); then
+          fi
+          wget_exit_code=$?
           if [ "$status_code" -eq 200 ]; then
             unzip artifactory_success_output/$ARTIFACTORY_ARTIFACT_NAME.zip -d artifactory_success_output
           elif [ "$status_code" -eq 404 ]; then
               echo "Error: File not found (Status code: $status_code). This means that the upload-object-changes.yml workflow was not run on ${{ github.sha }} as \
               a post deployment step on the develop branch. If this was a commit for a conflict fix on master, please merge it into develop first and then run the \
               upload-object-changes.yml workflow on the develop branch. You can then re-run this workflow."
+              echo "[error] wget threw error code: $wget_exit_code with status code: $status_code"
               exit 1
           else
-              echo "Received HTTP status code when pulling : $status_code"
+              echo "Error when pulling artifact from artfiactory. Received HTTP status code when pulling : $status_code"
+              echo "[error] wget threw error code: $wget_exit_code with status code: $status_code"
               exit 1
           fi
 
