fix artifactory pull issue

diff --git a/.github/workflows/validate-object-changes.yaml b/.github/workflows/validate-object-changes.yaml
--- a/.github/workflows/validate-object-changes.yaml
+++ b/.github/workflows/validate-object-changes.yaml
@@ -35,18 +35,20 @@ jobs:
           ARTIFACTORY_ARTIFACT_LINK=https://artifactory.gcp.anz/artifactory/anzx-salesforce-releases-np/$ARTIFACTORY_ARTIFACT_NAME.zip
           echo "ARTIFACTORY_ARTIFACT_LINK=$ARTIFACTORY_ARTIFACT_LINK"
           if  ! response=$(wget --server-response -P artifactory_success_output/ "$ARTIFACTORY_ARTIFACT_LINK" 2>&1); then
-              echo "Error when pulling artifact from artifactory:\n $response"
+          echo "Error when pulling artifact from artifactory:\n $response"
           fi
-          echo $response && status_code=`$response | awk '/HTTP\// {print $2}' | tail -n 1`
-          if [ $status_code -eq 200 ]; then
-            unzip artifactory_success_output/$ARTIFACTORY_ARTIFACT_NAME.zip -d artifactory_success_output
-          elif [ $status_code -eq 404 ]; then
-              echo "Error: File not found (Status code: $status_code). This means that the upload-object-changes.yml workflow was not run on ${{ github.sha }} as a post deployment step on the develop branch. If this was a commit for a conflict fix on master, please merge it into develop first and then run the upload-object-changes.yml workflow on the develop branch. You can then re-run this workflow."
-              echo "wget threw error with status code: $status_code"
-              exit 1
-          else
-              echo "wget threw error with status code: $status_code"
-              exit 1
+          status_code=$(echo "$response" | awk '/HTTP\// {print $2}' | tail -n 1)
+          if [ -n "$status_code" ]; then
+            if [ "$status_code" -eq 200 ]; then
+              unzip artifactory_success_output/$ARTIFACTORY_ARTIFACT_NAME.zip -d artifactory_success_output
+            elif [ "$status_code" -eq 404 ]; then
+                echo "Error: File not found (Status code: $status_code). This means that the upload-object-changes.yml workflow was not run on ${{ github.event.pull_request.head.sha }} as a post deployment step on the develop branch. If this was a commit for a conflict fix on master, please merge it into develop first and then run the upload-object-changes.yml workflow on the develop branch. You can then re-run this workflow."
+                echo "wget threw error with status code: $status_code"
+                exit 1
+            else
+                echo "wget threw error with status code: $status_code"
+                exit 1
+            fi
           fi
 
       - name: "Set up Cloud SDK"
